/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_addcap (void);
GtkWidget* create_gestcap (void);
GtkWidget* create_delcap (void);
GtkWidget* create_editcap (void);
GtkWidget* create_findcap (void);
GtkWidget* create_GestionEtudiants_am (void);
GtkWidget* create_AjouterEtudiant_am (void);
GtkWidget* create_ModifierEtudiant_am (void);
GtkWidget* create_ConfirmerAjout_am (void);
GtkWidget* create_ConfirmerSupression_am (void);
GtkWidget* create_ajouter_rec (void);
GtkWidget* create_Tree_view (void);
GtkWidget* create_supprimer_rec (void);
GtkWidget* create_service_plus_reclame (void);
GtkWidget* create_chercher_rec (void);
GtkWidget* create_modifier_rec (void);
GtkWidget* create_ajouter_user (void);
GtkWidget* create_gestion_des_utilisateurs (void);
GtkWidget* create_modifier_user (void);
GtkWidget* create_detection (void);
GtkWidget* create_stock_ab (void);
GtkWidget* create_chercher_ab (void);
GtkWidget* create_ajouter_ab (void);
GtkWidget* create_modifier_ab (void);
GtkWidget* create_retirer_ab (void);
GtkWidget* create_windowmain (void);
GtkWidget* create_windowlogin (void);
GtkWidget* create_windowespaceadmin (void);
GtkWidget* create_gestion_des_menus (void);
GtkWidget* create_ajouterdesmenus (void);
GtkWidget* create_suprime (void);
GtkWidget* create_modification (void);
GtkWidget* create_chercherdesmenus (void);
GtkWidget* create_con_supp (void);
GtkWidget* create_windowextras (void);
